# NOTE: This file is not designed to be run independently.
#
# Instead, use it with a file for a specific OS and Swift version, for example:
#
# % docker-compose \
#   -f docker/docker-compose.yaml \
#   -f docker/docker-compose.2204.59.yaml \
#   run test
#
version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-runtime:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: *image
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code

  soundness:
    <<: *common
    command: echo "skipping; moved to Github Actions"

  test:
    <<: *common
    command: echo "skipping; moved to Github Actions"

  shell:
    <<: *common
    entrypoint: /bin/bash

  integration-test:
    <<: *common
    command: echo "skipping; moved to Github Actions"

  docc-test:
    <<: *common
    command: echo "skipping; moved to Github Actions"
    environment:
      DOCC_TARGET: OpenAPIRuntime
