version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-runtime:22.04-5.10
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.10"

  test:
    image: *image
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      # Disabled strict concurrency checking as currently it's not possible to iterate an async sequence
      # from inside an actor without warnings.
      # - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: *image
